@startuml mcd

Class User {
    String username
    String email
    String password
    String archidekt_refresh_token
    String archidekt_access_token

}

Class Player {
    String name
}

Class Deck {
    String name
    String archidekt_id
    String games_played
    String games_won
    
}

Class Game {
    Number NumberOfPlayers
    String name
    Date database
}

Class Pod {
    String name
}

User "0..*" -- "0..1" Player
Player "1..1" -- "0..*" Pod
Player "0..*" -- "0..1" Deck
Pod "0..*" -- "1..1" Game
Deck "0..*" -- "1..*" Game : Players
Deck "0..*" -- "1..1" Game : Winner
